// next
import type { Metadata } from "next";
import localFont from "next/font/local";
// mui + styles
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import RTLProvider from "@/styles/rtlProvider";
import { ThemeProvider } from "@/utils/context/ThemeContext";
import { Box } from "@mui/material";
import "@/styles/globals.css";

const geistSans = localFont({
  src: "./../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const yekan = localFont({
  src: "./../public/fonts/Far_Yekan.ttf",
  variable: "--font-yekan",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Moochi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekan.variable} ${geistSans.variable} ${geistMono.variable}`}
      >
        <AppRouterCacheProvider>
          <ThemeProvider>
            <RTLProvider>
              <Box
                sx={{
                  minWidth: "100svw",
                  minHeight: "100svh",
                  bgcolor: "background.default",
                }}
              >
                {children}
              </Box>
            </RTLProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
